graph LR
 a[Zen] --> b[Keluarga] & c[Pekerjaan]
 b -- istri --> d[Tri Handayani]
 b -- anak --> e[Maryam Syafa Salsabila]
 c -- guru tahfidz --> f[Madrasah Baitul Izzah]
 c -- layouter --> g[Caraka Publishing]
 c -- mekanik --> h[Toko sepeda Sinar Jaya]