name: "deploy gitbook"
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      # We must check out the repo first
      - name: Checkout
        uses: actions/checkout@v2
      # Now run this publish action
      - name: Publish
        uses: tuliren/publish-gitbook@v1.0.0
        with:
          # specify either github_token or personal_token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.PERSONAL_TOKEN }}